# Generated by Django 3.0.5 on 2020-05-02 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name of the project', max_length=256, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Registration code', max_length=256, verbose_name='Code')),
                ('project', models.ForeignKey(help_text='Project to which this vehicle belongs', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='trans.Project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'unique_together': {('code', 'project')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(db_index=True, help_text='Time when the order is started', verbose_name='Start Time')),
                ('stop_time', models.DateTimeField(db_index=True, help_text='Time when the order is stopped', verbose_name='Stop Time')),
                ('client', models.ForeignKey(help_text='Client getting an order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('driver', models.ForeignKey(help_text='Driver assigned to this order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='trans.Driver', verbose_name='Driver')),
                ('project', models.ForeignKey(help_text='Project to which this order belongs', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='trans.Project', verbose_name='Project')),
                ('vehicle', models.ForeignKey(help_text='Vehicle assigned to this order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='trans.Vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='project',
            field=models.ForeignKey(help_text='Project to which this driver belongs', on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='trans.Project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.ForeignKey(help_text='User who is a driver', on_delete=django.db.models.deletion.CASCADE, related_name='driving', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_change', models.BooleanField(default=True, help_text='Is the member allowed to change the project data?', verbose_name='Allow Change')),
                ('allow_manage', models.BooleanField(default=False, help_text='Is the member allowed to manage users for the project?', verbose_name='Allow Manage')),
                ('project', models.ForeignKey(help_text='Project to which this user belongs', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='trans.Project', verbose_name='Project')),
                ('user', models.ForeignKey(help_text='User who belongs to this project', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Project Member',
                'verbose_name_plural': 'Project Members',
                'unique_together': {('user', 'project')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='driver',
            unique_together={('user', 'project')},
        ),
    ]
